[ming]

Enable = 0
Reset = 0
SellingItemsMax = 100
BuyingItemsMax = 10
BuyerId = 0
BuyerViewRate = 0.1
BuyerBuyRate = 1.0
ManagerCheckDelay = 60000
VenderReplaceDelay_Min = 3600000
VenderReplaceDelay_Max = 7200000